# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calcT0 <- function(tXUs, yresid, powV, nperm) {
    .Call('aSPUc_calcT0', PACKAGE = 'aSPUc', tXUs, yresid, powV, nperm)
}

calcT0sim <- function(CvSqrt, powV, nperm) {
    .Call('aSPUc_calcT0sim', PACKAGE = 'aSPUc', CvSqrt, powV, nperm)
}

calcT0simM2 <- function(A, B, powV, pow2V, nperm, Pval, Ts) {
    .Call('aSPUc_calcT0simM2', PACKAGE = 'aSPUc', A, B, powV, pow2V, nperm, Pval, Ts)
}

set_seed <- function(seed) {
    invisible(.Call('aSPUc_set_seed', PACKAGE = 'aSPUc', seed))
}

avg_rank <- function(x) {
    .Call('aSPUc_avg_rank', PACKAGE = 'aSPUc', x)
}

aSPUpathEngine <- function(tXUs, r, pow1, pow2, nGenes, n_perm, k, nSNPs0, Ts2, s) {
    .Call('aSPUc_aSPUpathEngine', PACKAGE = 'aSPUc', tXUs, r, pow1, pow2, nGenes, n_perm, k, nSNPs0, Ts2, s)
}

aSPUpermEngine <- function(tXUs, r, pow1, n_perm, Ts, s) {
    .Call('aSPUc_aSPUpermEngine', PACKAGE = 'aSPUc', tXUs, r, pow1, n_perm, Ts, s)
}

aSPUsPathEngine <- function(CH, CHcovSq, pow1, pow2, nGenes, n_perm, k, Ps, nSNPs0, StdTs) {
    .Call('aSPUc_aSPUsPathEngine', PACKAGE = 'aSPUc', CH, CHcovSq, pow1, pow2, nGenes, n_perm, k, Ps, nSNPs0, StdTs)
}

aSPUsPathEngine2 <- function(CH, CHcovSq, pow1, pow2, nGenes, n_perm, k, Ps, nSNPs0, Ts2, s) {
    .Call('aSPUc_aSPUsPathEngine2', PACKAGE = 'aSPUc', CH, CHcovSq, pow1, pow2, nGenes, n_perm, k, Ps, nSNPs0, Ts2, s)
}

